# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.create_order_request_initial_payment import CreateOrderRequestInitialPayment

class TestCreateOrderRequestInitialPayment(unittest.TestCase):
    """CreateOrderRequestInitialPayment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateOrderRequestInitialPayment:
        """Test CreateOrderRequestInitialPayment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOrderRequestInitialPayment`
        """
        model = CreateOrderRequestInitialPayment()
        if include_optional:
            return CreateOrderRequestInitialPayment(
                code = '',
                additional_info = '',
                amount = order.models.order_money.orderMoney(
                    units = '', 
                    micros = 56, ),
                cc_info = order.models.payment_cc_info.PaymentCcInfo(
                    approval = '', 
                    exp_month = 56, 
                    exp_year = '', 
                    last4 = '', 
                    number_enc = '', 
                    owner = '', 
                    avs_status = '', 
                    type = '', ),
                transaction = order.models.initial_payment_initial_transaction.InitialPaymentInitialTransaction(
                    type = 'UNKNOWN', 
                    additional_info = '', )
            )
        else:
            return CreateOrderRequestInitialPayment(
        )
        """

    def testCreateOrderRequestInitialPayment(self):
        """Test CreateOrderRequestInitialPayment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
