# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_print_orders_labels_response import OrderPrintOrdersLabelsResponse

class TestOrderPrintOrdersLabelsResponse(unittest.TestCase):
    """OrderPrintOrdersLabelsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderPrintOrdersLabelsResponse:
        """Test OrderPrintOrdersLabelsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderPrintOrdersLabelsResponse`
        """
        model = OrderPrintOrdersLabelsResponse()
        if include_optional:
            return OrderPrintOrdersLabelsResponse(
                download_url = '',
                failed_orders = [
                    order.models.print_orders_labels_response_failed_order.PrintOrdersLabelsResponseFailedOrder(
                        order_number = '', 
                        error_message = '', 
                        error_code = '', )
                    ]
            )
        else:
            return OrderPrintOrdersLabelsResponse(
        )
        """

    def testOrderPrintOrdersLabelsResponse(self):
        """Test OrderPrintOrdersLabelsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
