# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_payment import OrderPayment

class TestOrderPayment(unittest.TestCase):
    """OrderPayment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderPayment:
        """Test OrderPayment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderPayment`
        """
        model = OrderPayment()
        if include_optional:
            return OrderPayment(
                order_id = '',
                id = '',
                code = '',
                additional_info = '',
                amounts = [
                    order.models.order_payment_amount.orderPaymentAmount(
                        code = 'UNKNOWN', 
                        value = order.models.order_money.orderMoney(
                            units = '', 
                            micros = 56, ), )
                    ],
                cc_info = order.models.payment_cc_info.PaymentCcInfo(
                    approval = '', 
                    exp_month = 56, 
                    exp_year = '', 
                    last4 = '', 
                    number_enc = '', 
                    owner = '', 
                    avs_status = '', 
                    type = '', ),
                transactions = [
                    order.models.order_transaction.orderTransaction(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        payment_id = '', 
                        id = '', 
                        type = 'UNKNOWN', 
                        additional_info = '', 
                        child_transactions = [
                            order.models.order_transaction.orderTransaction(
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                payment_id = '', 
                                id = '', 
                                additional_info = '', )
                            ], )
                    ]
            )
        else:
            return OrderPayment(
        )
        """

    def testOrderPayment(self):
        """Test OrderPayment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
