# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_payment_amount_code import OrderPaymentAmountCode

class TestOrderPaymentAmountCode(unittest.TestCase):
    """OrderPaymentAmountCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderPaymentAmountCode(self):
        """Test OrderPaymentAmountCode"""
        # inst = OrderPaymentAmountCode()

if __name__ == '__main__':
    unittest.main()
