# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_refund_amount import OrderRefundAmount

class TestOrderRefundAmount(unittest.TestCase):
    """OrderRefundAmount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderRefundAmount:
        """Test OrderRefundAmount
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderRefundAmount`
        """
        model = OrderRefundAmount()
        if include_optional:
            return OrderRefundAmount(
                code = 'UNKNOWN',
                value = order.models.order_money.orderMoney(
                    units = '', 
                    micros = 56, )
            )
        else:
            return OrderRefundAmount(
        )
        """

    def testOrderRefundAmount(self):
        """Test OrderRefundAmount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
