# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_list_orders_by_numbers_request import OrderListOrdersByNumbersRequest

class TestOrderListOrdersByNumbersRequest(unittest.TestCase):
    """OrderListOrdersByNumbersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderListOrdersByNumbersRequest:
        """Test OrderListOrdersByNumbersRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderListOrdersByNumbersRequest`
        """
        model = OrderListOrdersByNumbersRequest()
        if include_optional:
            return OrderListOrdersByNumbersRequest(
                tenant_id = '',
                numbers = [
                    ''
                    ],
                page_size = 56,
                page_token = ''
            )
        else:
            return OrderListOrdersByNumbersRequest(
        )
        """

    def testOrderListOrdersByNumbersRequest(self):
        """Test OrderListOrdersByNumbersRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
