# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_data_shipment_info import OrderDataShipmentInfo

class TestOrderDataShipmentInfo(unittest.TestCase):
    """OrderDataShipmentInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderDataShipmentInfo:
        """Test OrderDataShipmentInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderDataShipmentInfo`
        """
        model = OrderDataShipmentInfo()
        if include_optional:
            return OrderDataShipmentInfo(
                reference = '',
                code = '',
                method = '',
                title = '',
                additional_info = '',
                amount = order.models.order_money.orderMoney(
                    units = '', 
                    micros = 56, ),
                fee = order.models.order_money.orderMoney(
                    units = '', 
                    micros = 56, ),
                vat_amount = order.models.order_money.orderMoney(
                    units = '', 
                    micros = 56, ),
                vat_percentage = 1.337,
                vat_inaccurate = True,
                vat_calculated = True,
                grn = '',
                from_address = order.models.order_postal_address.orderPostalAddress(
                    revision = 56, 
                    region_code = '', 
                    language_code = '', 
                    postal_code = '', 
                    sorting_code = '', 
                    administrative_area = '', 
                    locality = '', 
                    sublocality = '', 
                    address_lines = [
                        ''
                        ], 
                    recipients = [
                        ''
                        ], 
                    organization = '', 
                    phone_number = '', 
                    additional_info = order.models.additional_info.additionalInfo(), ),
                return_address = order.models.order_postal_address.orderPostalAddress(
                    revision = 56, 
                    region_code = '', 
                    language_code = '', 
                    postal_code = '', 
                    sorting_code = '', 
                    administrative_area = '', 
                    locality = '', 
                    sublocality = '', 
                    address_lines = [
                        ''
                        ], 
                    recipients = [
                        ''
                        ], 
                    organization = '', 
                    phone_number = '', 
                    additional_info = order.models.additional_info.additionalInfo(), )
            )
        else:
            return OrderDataShipmentInfo(
        )
        """

    def testOrderDataShipmentInfo(self):
        """Test OrderDataShipmentInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
