# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_calculate_refund_response import OrderCalculateRefundResponse

class TestOrderCalculateRefundResponse(unittest.TestCase):
    """OrderCalculateRefundResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderCalculateRefundResponse:
        """Test OrderCalculateRefundResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderCalculateRefundResponse`
        """
        model = OrderCalculateRefundResponse()
        if include_optional:
            return OrderCalculateRefundResponse(
                create_refund_request = order.models.order_create_refund_request.orderCreateRefundRequest(
                    tenant_id = '', 
                    payment_id = '', 
                    items = [
                        order.models.order_refund_item.orderRefundItem(
                            order_item_id = '', 
                            qty = 56, )
                        ], 
                    amounts = [
                        order.models.order_refund_amount.orderRefundAmount(
                            code = 'UNKNOWN', 
                            value = order.models.order_money.orderMoney(
                                units = '', 
                                micros = 56, ), )
                        ], 
                    note = '', 
                    additional_info = '', )
            )
        else:
            return OrderCalculateRefundResponse(
        )
        """

    def testOrderCalculateRefundResponse(self):
        """Test OrderCalculateRefundResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
