# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.payment_cc_info import PaymentCcInfo

class TestPaymentCcInfo(unittest.TestCase):
    """PaymentCcInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentCcInfo:
        """Test PaymentCcInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentCcInfo`
        """
        model = PaymentCcInfo()
        if include_optional:
            return PaymentCcInfo(
                approval = '',
                exp_month = 56,
                exp_year = '',
                last4 = '',
                number_enc = '',
                owner = '',
                avs_status = '',
                type = ''
            )
        else:
            return PaymentCcInfo(
        )
        """

    def testPaymentCcInfo(self):
        """Test PaymentCcInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
