# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.behavior_options_payment_action import BehaviorOptionsPaymentAction

class TestBehaviorOptionsPaymentAction(unittest.TestCase):
    """BehaviorOptionsPaymentAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBehaviorOptionsPaymentAction(self):
        """Test BehaviorOptionsPaymentAction"""
        # inst = BehaviorOptionsPaymentAction()

if __name__ == '__main__':
    unittest.main()
