# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_currency import OrderCurrency

class TestOrderCurrency(unittest.TestCase):
    """OrderCurrency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderCurrency(self):
        """Test OrderCurrency"""
        # inst = OrderCurrency()

if __name__ == '__main__':
    unittest.main()
