# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_list_orders_request import OrderListOrdersRequest

class TestOrderListOrdersRequest(unittest.TestCase):
    """OrderListOrdersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderListOrdersRequest:
        """Test OrderListOrdersRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderListOrdersRequest`
        """
        model = OrderListOrdersRequest()
        if include_optional:
            return OrderListOrdersRequest(
                tenant_id = '',
                page_size = 56,
                page_token = '',
                order_by = [
                    order.models.order_order_by.orderOrderBy(
                        field = '', 
                        direction = 'DEFAULT', )
                    ],
                status_filter = order.models.order_status_filter.orderStatusFilter(
                    statuses = [
                        ''
                        ], 
                    condition = 'IN', )
            )
        else:
            return OrderListOrdersRequest(
                tenant_id = '',
        )
        """

    def testOrderListOrdersRequest(self):
        """Test OrderListOrdersRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
