# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_order_by import OrderOrderBy

class TestOrderOrderBy(unittest.TestCase):
    """OrderOrderBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderOrderBy:
        """Test OrderOrderBy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderOrderBy`
        """
        model = OrderOrderBy()
        if include_optional:
            return OrderOrderBy(
                field = '',
                direction = 'DEFAULT'
            )
        else:
            return OrderOrderBy(
        )
        """

    def testOrderOrderBy(self):
        """Test OrderOrderBy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
