# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_hold_order_request import OrderHoldOrderRequest

class TestOrderHoldOrderRequest(unittest.TestCase):
    """OrderHoldOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderHoldOrderRequest:
        """Test OrderHoldOrderRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderHoldOrderRequest`
        """
        model = OrderHoldOrderRequest()
        if include_optional:
            return OrderHoldOrderRequest(
                tenant_id = '',
                order_id = '',
                reason = ''
            )
        else:
            return OrderHoldOrderRequest(
                order_id = '',
        )
        """

    def testOrderHoldOrderRequest(self):
        """Test OrderHoldOrderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
