# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.product_configuration_step_option import ProductConfigurationStepOption

class TestProductConfigurationStepOption(unittest.TestCase):
    """ProductConfigurationStepOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductConfigurationStepOption:
        """Test ProductConfigurationStepOption
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductConfigurationStepOption`
        """
        model = ProductConfigurationStepOption()
        if include_optional:
            return ProductConfigurationStepOption(
                id = '',
                grn = '',
                label = '',
                price_variation = order.models.order_money.orderMoney(
                    units = '', 
                    micros = 56, ),
                image = order.models.option_image.OptionImage(
                    grn = '', 
                    url = '', ),
                has_quantity = True,
                quantity = 56
            )
        else:
            return ProductConfigurationStepOption(
        )
        """

    def testProductConfigurationStepOption(self):
        """Test ProductConfigurationStepOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
