# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_data_promotion_info import OrderDataPromotionInfo

class TestOrderDataPromotionInfo(unittest.TestCase):
    """OrderDataPromotionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderDataPromotionInfo:
        """Test OrderDataPromotionInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderDataPromotionInfo`
        """
        model = OrderDataPromotionInfo()
        if include_optional:
            return OrderDataPromotionInfo(
                promotion_grn = '',
                type = '',
                additional_info = '',
                name = '',
                description = '',
                amount = order.models.order_money.orderMoney(
                    units = '', 
                    micros = 56, ),
                coupon_code = '',
                vat_amount = order.models.order_money.orderMoney(
                    units = '', 
                    micros = 56, ),
                vat_percentage = 1.337,
                vat_inaccurate = True,
                vat_calculated = True
            )
        else:
            return OrderDataPromotionInfo(
        )
        """

    def testOrderDataPromotionInfo(self):
        """Test OrderDataPromotionInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
