# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_create_payment_transaction_request import OrderCreatePaymentTransactionRequest

class TestOrderCreatePaymentTransactionRequest(unittest.TestCase):
    """OrderCreatePaymentTransactionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderCreatePaymentTransactionRequest:
        """Test OrderCreatePaymentTransactionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderCreatePaymentTransactionRequest`
        """
        model = OrderCreatePaymentTransactionRequest()
        if include_optional:
            return OrderCreatePaymentTransactionRequest(
                tenant_id = '',
                payment_id = '',
                type = 'UNKNOWN',
                additional_info = ''
            )
        else:
            return OrderCreatePaymentTransactionRequest(
                tenant_id = '',
                payment_id = '',
                type = 'UNKNOWN',
        )
        """

    def testOrderCreatePaymentTransactionRequest(self):
        """Test OrderCreatePaymentTransactionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
