# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_resolve_shipment_missing_stock_request import OrderResolveShipmentMissingStockRequest

class TestOrderResolveShipmentMissingStockRequest(unittest.TestCase):
    """OrderResolveShipmentMissingStockRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderResolveShipmentMissingStockRequest:
        """Test OrderResolveShipmentMissingStockRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderResolveShipmentMissingStockRequest`
        """
        model = OrderResolveShipmentMissingStockRequest()
        if include_optional:
            return OrderResolveShipmentMissingStockRequest(
                tenant_id = '',
                shipment_id = ''
            )
        else:
            return OrderResolveShipmentMissingStockRequest(
                tenant_id = '',
                shipment_id = '',
        )
        """

    def testOrderResolveShipmentMissingStockRequest(self):
        """Test OrderResolveShipmentMissingStockRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
