# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_status_filter_condition import OrderStatusFilterCondition

class TestOrderStatusFilterCondition(unittest.TestCase):
    """OrderStatusFilterCondition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderStatusFilterCondition(self):
        """Test OrderStatusFilterCondition"""
        # inst = OrderStatusFilterCondition()

if __name__ == '__main__':
    unittest.main()
