# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_cancel_shipment_request import OrderCancelShipmentRequest

class TestOrderCancelShipmentRequest(unittest.TestCase):
    """OrderCancelShipmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderCancelShipmentRequest:
        """Test OrderCancelShipmentRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderCancelShipmentRequest`
        """
        model = OrderCancelShipmentRequest()
        if include_optional:
            return OrderCancelShipmentRequest(
                tenant_id = '',
                shipment_id = '',
                reason = ''
            )
        else:
            return OrderCancelShipmentRequest(
        )
        """

    def testOrderCancelShipmentRequest(self):
        """Test OrderCancelShipmentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
