# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.behavior_options_inventory import BehaviorOptionsInventory

class TestBehaviorOptionsInventory(unittest.TestCase):
    """BehaviorOptionsInventory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BehaviorOptionsInventory:
        """Test BehaviorOptionsInventory
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BehaviorOptionsInventory`
        """
        model = BehaviorOptionsInventory()
        if include_optional:
            return BehaviorOptionsInventory(
                action = 'UNKNOWN'
            )
        else:
            return BehaviorOptionsInventory(
        )
        """

    def testBehaviorOptionsInventory(self):
        """Test BehaviorOptionsInventory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
