# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_send_fulfillment_request import OrderSendFulfillmentRequest

class TestOrderSendFulfillmentRequest(unittest.TestCase):
    """OrderSendFulfillmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderSendFulfillmentRequest:
        """Test OrderSendFulfillmentRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderSendFulfillmentRequest`
        """
        model = OrderSendFulfillmentRequest()
        if include_optional:
            return OrderSendFulfillmentRequest(
                tenant_id = '',
                fulfillment_id = ''
            )
        else:
            return OrderSendFulfillmentRequest(
                tenant_id = '',
                fulfillment_id = '',
        )
        """

    def testOrderSendFulfillmentRequest(self):
        """Test OrderSendFulfillmentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
