# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_search_orders_request import OrderSearchOrdersRequest

class TestOrderSearchOrdersRequest(unittest.TestCase):
    """OrderSearchOrdersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderSearchOrdersRequest:
        """Test OrderSearchOrdersRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderSearchOrdersRequest`
        """
        model = OrderSearchOrdersRequest()
        if include_optional:
            return OrderSearchOrdersRequest(
                tenant_id = '',
                search_query = '',
                page_size = 56,
                page_token = '',
                order_by = [
                    order.models.order_order_by.orderOrderBy(
                        field = '', 
                        direction = 'DEFAULT', )
                    ],
                status_filter = order.models.order_status_filter.orderStatusFilter(
                    statuses = [
                        ''
                        ], 
                    condition = 'IN', ),
                from_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                to_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                payment_filter = order.models.order_payment_filter.orderPaymentFilter(
                    codes = [
                        ''
                        ], 
                    condition = 'IN', ),
                agent_grn = ''
            )
        else:
            return OrderSearchOrdersRequest(
                tenant_id = '',
        )
        """

    def testOrderSearchOrdersRequest(self):
        """Test OrderSearchOrdersRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
