# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.import_order_request_imported_payment import ImportOrderRequestImportedPayment

class TestImportOrderRequestImportedPayment(unittest.TestCase):
    """ImportOrderRequestImportedPayment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportOrderRequestImportedPayment:
        """Test ImportOrderRequestImportedPayment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportOrderRequestImportedPayment`
        """
        model = ImportOrderRequestImportedPayment()
        if include_optional:
            return ImportOrderRequestImportedPayment(
                code = '',
                additional_info = '',
                amounts = [
                    order.models.order_payment_amount.orderPaymentAmount(
                        code = 'UNKNOWN', 
                        value = order.models.order_money.orderMoney(
                            units = '', 
                            micros = 56, ), )
                    ],
                cc_info = order.models.payment_cc_info.PaymentCcInfo(
                    approval = '', 
                    exp_month = 56, 
                    exp_year = '', 
                    last4 = '', 
                    number_enc = '', 
                    owner = '', 
                    avs_status = '', 
                    type = '', ),
                is_upfront = True
            )
        else:
            return ImportOrderRequestImportedPayment(
                code = '',
                amounts = [
                    order.models.order_payment_amount.orderPaymentAmount(
                        code = 'UNKNOWN', 
                        value = order.models.order_money.orderMoney(
                            units = '', 
                            micros = 56, ), )
                    ],
        )
        """

    def testImportOrderRequestImportedPayment(self):
        """Test ImportOrderRequestImportedPayment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
