# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from order.models.order_update_order_request import OrderUpdateOrderRequest

class TestOrderUpdateOrderRequest(unittest.TestCase):
    """OrderUpdateOrderRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderUpdateOrderRequest:
        """Test OrderUpdateOrderRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderUpdateOrderRequest`
        """
        model = OrderUpdateOrderRequest()
        if include_optional:
            return OrderUpdateOrderRequest(
                tenant_id = '',
                id = '',
                payload = order.models.update_order_request_payload.UpdateOrderRequestPayload(
                    billing_address = order.models.order_postal_address.orderPostalAddress(
                        revision = 56, 
                        region_code = '', 
                        language_code = '', 
                        postal_code = '', 
                        sorting_code = '', 
                        administrative_area = '', 
                        locality = '', 
                        sublocality = '', 
                        address_lines = [
                            ''
                            ], 
                        recipients = [
                            ''
                            ], 
                        organization = '', 
                        phone_number = '', 
                        additional_info = order.models.additional_info.additionalInfo(), ), 
                    shipping_address = order.models.order_postal_address.orderPostalAddress(
                        revision = 56, 
                        region_code = '', 
                        language_code = '', 
                        postal_code = '', 
                        sorting_code = '', 
                        administrative_area = '', 
                        locality = '', 
                        sublocality = '', 
                        organization = '', 
                        phone_number = '', 
                        additional_info = order.models.additional_info.additionalInfo(), ), 
                    additional_info = order.models.additional_info.additionalInfo(), ),
                field_mask = [
                    ''
                    ]
            )
        else:
            return OrderUpdateOrderRequest(
        )
        """

    def testOrderUpdateOrderRequest(self):
        """Test OrderUpdateOrderRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
