# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from order.models.initial_payment_initial_transaction import InitialPaymentInitialTransaction
from order.models.order_money import OrderMoney
from order.models.payment_cc_info import PaymentCcInfo
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CreateOrderRequestInitialPayment(BaseModel):
    """
    CreateOrderRequestInitialPayment
    """ # noqa: E501
    code: StrictStr
    additional_info: Optional[StrictStr] = Field(default=None, alias="additionalInfo")
    amount: OrderMoney
    cc_info: Optional[PaymentCcInfo] = Field(default=None, alias="ccInfo")
    transaction: Optional[InitialPaymentInitialTransaction] = None
    __properties: ClassVar[List[str]] = ["code", "additionalInfo", "amount", "ccInfo", "transaction"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CreateOrderRequestInitialPayment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of amount
        if self.amount:
            _dict['amount'] = self.amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cc_info
        if self.cc_info:
            _dict['ccInfo'] = self.cc_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transaction
        if self.transaction:
            _dict['transaction'] = self.transaction.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CreateOrderRequestInitialPayment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "additionalInfo": obj.get("additionalInfo"),
            "amount": OrderMoney.from_dict(obj.get("amount")) if obj.get("amount") is not None else None,
            "ccInfo": PaymentCcInfo.from_dict(obj.get("ccInfo")) if obj.get("ccInfo") is not None else None,
            "transaction": InitialPaymentInitialTransaction.from_dict(obj.get("transaction")) if obj.get("transaction") is not None else None
        })
        return _obj


