# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class OrderDataCustomerInfo(BaseModel):
    """
    OrderDataCustomerInfo
    """ # noqa: E501
    grn: Optional[StrictStr] = None
    firstname: StrictStr
    lastname: StrictStr
    email: StrictStr
    phone: Optional[StrictStr] = None
    segment: Optional[StrictStr] = None
    data: Optional[StrictStr] = None
    certified_email: Optional[StrictStr] = Field(default=None, alias="certifiedEmail")
    tax_code: Optional[StrictStr] = Field(default=None, alias="taxCode")
    sdi_code: Optional[StrictStr] = Field(default=None, alias="sdiCode")
    fiscal_code: Optional[StrictStr] = Field(default=None, alias="fiscalCode")
    company_name: Optional[StrictStr] = Field(default=None, alias="companyName")
    agent_grn: Optional[StrictStr] = Field(default=None, alias="agentGrn")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["grn", "firstname", "lastname", "email", "phone", "segment", "data", "certifiedEmail", "taxCode", "sdiCode", "fiscalCode", "companyName", "agentGrn"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderDataCustomerInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderDataCustomerInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "grn": obj.get("grn"),
            "firstname": obj.get("firstname"),
            "lastname": obj.get("lastname"),
            "email": obj.get("email"),
            "phone": obj.get("phone"),
            "segment": obj.get("segment"),
            "data": obj.get("data"),
            "certifiedEmail": obj.get("certifiedEmail"),
            "taxCode": obj.get("taxCode"),
            "sdiCode": obj.get("sdiCode"),
            "fiscalCode": obj.get("fiscalCode"),
            "companyName": obj.get("companyName"),
            "agentGrn": obj.get("agentGrn")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


