# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from order.models.order_refund_amount import OrderRefundAmount
from order.models.order_refund_item import OrderRefundItem
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OrderRefund(BaseModel):
    """
    OrderRefund
    """ # noqa: E501
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    payment_id: Optional[StrictStr] = Field(default=None, alias="paymentId")
    id: Optional[StrictStr] = None
    items: Optional[List[OrderRefundItem]] = None
    amounts: Optional[List[OrderRefundAmount]] = None
    note: Optional[StrictStr] = None
    additional_info: Optional[StrictStr] = Field(default=None, alias="additionalInfo")
    transaction_ids: Optional[List[StrictStr]] = Field(default=None, alias="transactionIds")
    __properties: ClassVar[List[str]] = ["createdAt", "paymentId", "id", "items", "amounts", "note", "additionalInfo", "transactionIds"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderRefund from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item in self.items:
                if _item:
                    _items.append(_item.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in amounts (list)
        _items = []
        if self.amounts:
            for _item in self.amounts:
                if _item:
                    _items.append(_item.to_dict())
            _dict['amounts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OrderRefund from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "paymentId": obj.get("paymentId"),
            "id": obj.get("id"),
            "items": [OrderRefundItem.from_dict(_item) for _item in obj.get("items")] if obj.get("items") is not None else None,
            "amounts": [OrderRefundAmount.from_dict(_item) for _item in obj.get("amounts")] if obj.get("amounts") is not None else None,
            "note": obj.get("note"),
            "additionalInfo": obj.get("additionalInfo"),
            "transactionIds": obj.get("transactionIds")
        })
        return _obj


