# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from order.models.import_order_request_imported_payment import ImportOrderRequestImportedPayment
from order.models.order_currency import OrderCurrency
from order.models.order_data_customer_info import OrderDataCustomerInfo
from order.models.order_data_payment_info import OrderDataPaymentInfo
from order.models.order_data_shipment_info import OrderDataShipmentInfo
from order.models.order_data_subtotal import OrderDataSubtotal
from order.models.order_data_total import OrderDataTotal
from order.models.order_order_data_item import OrderOrderDataItem
from order.models.order_postal_address import OrderPostalAddress
from typing import Optional, Set
from typing_extensions import Self

class OrderImportOrderRequest(BaseModel):
    """
    OrderImportOrderRequest
    """ # noqa: E501
    tenant_id: StrictStr = Field(alias="tenantId")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    number: StrictStr
    channel: Optional[StrictStr] = None
    market: StrictStr
    locale: StrictStr
    customer_info: OrderDataCustomerInfo = Field(alias="customerInfo")
    shipping_address: OrderPostalAddress = Field(alias="shippingAddress")
    billing_address: OrderPostalAddress = Field(alias="billingAddress")
    payments: List[ImportOrderRequestImportedPayment]
    payments_info: List[OrderDataPaymentInfo] = Field(alias="paymentsInfo")
    shipments_info: List[OrderDataShipmentInfo] = Field(alias="shipmentsInfo")
    items: List[OrderOrderDataItem]
    subtotals: Dict[str, OrderDataSubtotal]
    totals: Dict[str, OrderDataTotal]
    status: StrictStr
    currency: OrderCurrency
    vat_included: Optional[StrictBool] = Field(default=None, alias="vatIncluded")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["tenantId", "createdAt", "number", "channel", "market", "locale", "customerInfo", "shippingAddress", "billingAddress", "payments", "paymentsInfo", "shipmentsInfo", "items", "subtotals", "totals", "status", "currency", "vatIncluded"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrderImportOrderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of customer_info
        if self.customer_info:
            _dict['customerInfo'] = self.customer_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of shipping_address
        if self.shipping_address:
            _dict['shippingAddress'] = self.shipping_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of billing_address
        if self.billing_address:
            _dict['billingAddress'] = self.billing_address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in payments (list)
        _items = []
        if self.payments:
            for _item_payments in self.payments:
                if _item_payments:
                    _items.append(_item_payments.to_dict())
            _dict['payments'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in payments_info (list)
        _items = []
        if self.payments_info:
            for _item_payments_info in self.payments_info:
                if _item_payments_info:
                    _items.append(_item_payments_info.to_dict())
            _dict['paymentsInfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in shipments_info (list)
        _items = []
        if self.shipments_info:
            for _item_shipments_info in self.shipments_info:
                if _item_shipments_info:
                    _items.append(_item_shipments_info.to_dict())
            _dict['shipmentsInfo'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in subtotals (dict)
        _field_dict = {}
        if self.subtotals:
            for _key_subtotals in self.subtotals:
                if self.subtotals[_key_subtotals]:
                    _field_dict[_key_subtotals] = self.subtotals[_key_subtotals].to_dict()
            _dict['subtotals'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in totals (dict)
        _field_dict = {}
        if self.totals:
            for _key_totals in self.totals:
                if self.totals[_key_totals]:
                    _field_dict[_key_totals] = self.totals[_key_totals].to_dict()
            _dict['totals'] = _field_dict
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrderImportOrderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenantId": obj.get("tenantId"),
            "createdAt": obj.get("createdAt"),
            "number": obj.get("number"),
            "channel": obj.get("channel"),
            "market": obj.get("market"),
            "locale": obj.get("locale"),
            "customerInfo": OrderDataCustomerInfo.from_dict(obj["customerInfo"]) if obj.get("customerInfo") is not None else None,
            "shippingAddress": OrderPostalAddress.from_dict(obj["shippingAddress"]) if obj.get("shippingAddress") is not None else None,
            "billingAddress": OrderPostalAddress.from_dict(obj["billingAddress"]) if obj.get("billingAddress") is not None else None,
            "payments": [ImportOrderRequestImportedPayment.from_dict(_item) for _item in obj["payments"]] if obj.get("payments") is not None else None,
            "paymentsInfo": [OrderDataPaymentInfo.from_dict(_item) for _item in obj["paymentsInfo"]] if obj.get("paymentsInfo") is not None else None,
            "shipmentsInfo": [OrderDataShipmentInfo.from_dict(_item) for _item in obj["shipmentsInfo"]] if obj.get("shipmentsInfo") is not None else None,
            "items": [OrderOrderDataItem.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None,
            "subtotals": dict(
                (_k, OrderDataSubtotal.from_dict(_v))
                for _k, _v in obj["subtotals"].items()
            )
            if obj.get("subtotals") is not None
            else None,
            "totals": dict(
                (_k, OrderDataTotal.from_dict(_v))
                for _k, _v in obj["totals"].items()
            )
            if obj.get("totals") is not None
            else None,
            "status": obj.get("status"),
            "currency": obj.get("currency") if obj.get("currency") is not None else OrderCurrency.XXX,
            "vatIncluded": obj.get("vatIncluded")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


