# coding: utf-8

"""
    order Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from order.models.order_payment_amount import OrderPaymentAmount
from order.models.order_transaction import OrderTransaction
from order.models.payment_cc_info import PaymentCcInfo
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OrderPayment(BaseModel):
    """
    OrderPayment
    """ # noqa: E501
    order_id: Optional[StrictStr] = Field(default=None, alias="orderId")
    id: Optional[StrictStr] = None
    code: Optional[StrictStr] = None
    additional_info: Optional[StrictStr] = Field(default=None, alias="additionalInfo")
    amounts: Optional[List[OrderPaymentAmount]] = None
    cc_info: Optional[PaymentCcInfo] = Field(default=None, alias="ccInfo")
    transactions: Optional[List[OrderTransaction]] = None
    __properties: ClassVar[List[str]] = ["orderId", "id", "code", "additionalInfo", "amounts", "ccInfo", "transactions"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderPayment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in amounts (list)
        _items = []
        if self.amounts:
            for _item in self.amounts:
                if _item:
                    _items.append(_item.to_dict())
            _dict['amounts'] = _items
        # override the default output from pydantic by calling `to_dict()` of cc_info
        if self.cc_info:
            _dict['ccInfo'] = self.cc_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in transactions (list)
        _items = []
        if self.transactions:
            for _item in self.transactions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['transactions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OrderPayment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "orderId": obj.get("orderId"),
            "id": obj.get("id"),
            "code": obj.get("code"),
            "additionalInfo": obj.get("additionalInfo"),
            "amounts": [OrderPaymentAmount.from_dict(_item) for _item in obj.get("amounts")] if obj.get("amounts") is not None else None,
            "ccInfo": PaymentCcInfo.from_dict(obj.get("ccInfo")) if obj.get("ccInfo") is not None else None,
            "transactions": [OrderTransaction.from_dict(_item) for _item in obj.get("transactions")] if obj.get("transactions") is not None else None
        })
        return _obj


